#!/usr/bin/env sh

# Per app configs
yabai -m rule --add app="^iTerm2$" space=1
yabai -m rule --add app="^kitty$" space=1
yabai -m rule --add app="^Code$" space=2 manage=off
yabai -m rule --add app="^Code" space=2 manage=off
yabai -m rule --add app="^Slack$" space=4
yabai -m rule --add app="^Things$" title!="Quick Entry| " space=3
yabai -m rule --add app="^Fantastical$" space=3
yabai -m rule --add app="^Spotify$" space=6
yabai -m rule --add app="WhatsApp" space=8 manage=on
yabai -m rule --add app="^Discord$" space=8 manage=off
yabai -m rule --add app="^Notion$" space=9
yabai -m rule --add app="^1Password$" manage=off role="AXWindow" subrole="AXStandardWindow"
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="FaceTime" manage=off
yabai -m rule --add app="The Unarchiver" manage=off
yabai -m rule --add app="Finder$" manage=off sub-layer=above
yabai -m rule --add app="^Calculator$" manage=off sub-layer=above
yabai -m rule --add app="^Activity Monitor$" manage=off sub-layer=above
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Studio 3T$" title="Connection Manager|New Connection" manage=off
yabai -m rule --add app="^Deluge$" title="Add|Choose" manage=off
yabai -m rule --add app="^zoom\.us$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^Plex Media Player$" manage=off


yabai -m rule --apply

echo "yabai configuration loaded.."